### ISSUE TITLE
input plugininde notice veriyor. 

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#10]
Merhaba, Controller'a herhangi bir key göndermediğimde. notice veriyor. bunu kontrol etmek için başka bir işlem mi yapmak gerekir.

**Comment by tkaratug** [comment]
Sorunu tam olarak anlayamadım. Input plugininde tam olarak nerde alıyorsunuz hatayı?

**Comment by abdurrahmanekr** [comment]
şimdi siteye bir post işlemi gerçekleştiğinde $_POST["deger"] şeklinde alıyoruz. ama deger boş gelirse normal olarak notice veriyor. Ben burada `isset($_POST[$data]) ? $_POST[$data] : null` şeklinde kullanılması tarafındayım

**Comment by tkaratug** [comment]
Öncelikle form verilerini aldığınız methodda önce post işlemi yapılıp yapılmadığını kontrol edin. 
`if($this->input->post())` koşulunun içerisinde form elemanlarını alabilirsiniz.

**Comment by abdurrahmanekr** [comment]
O şekilde yaparsak post olabilir ama içinde 'deger' olmayabilir. Aynı sorunla yine karşılaştım.

**Comment by tkaratug** [comment]
İçinde değer olmadan gönderseniz de sorun çıkarmaması gerek. Ben şu anda yaşadığınız hatayı yaratamıyorum. Veri boş gittiğinde boş değer döndürüyor.

**Comment by abdurrahmanekr** [comment]
`Notice: Undefined index: edit in /var/www/html/avarekodcu/system/plugins/Input.php on line 91
` şeklinde verdi controller'ım içindeki fonksiyonlar 
```
public function __construct()
{
	parent::__construct();
	$this->load->plugin('session');
	$this->load->plugin('input');
	$this->load->plugin('template');

	if ($this->session->is_exists('admin')) {
		if (!$this->session->get('admin')) {
			$this->load->view('admin/login_view');
			die();
		}
	}
	else {
		redirect(base_url());
		die();
	}
}

public function index()
{
	$edit = $this->input->post('edit');
	if ($edit)
		$edit = $this->SubjectModel->getSubject($edit);
	$this->load->view('admin/subject_view', [
		"edit" => $edit
	]);
}
```
şeklinde yaptım `index.php ` deki environment şu şekilde `define('ENVIRONMENT', 'development');` aslında hata vermiyor notice veriyor önemli bir sorun değil ama yinede belirtmek istedim

**Comment by tkaratug** [comment]
Sorun postun boş dönmesinden kaynaklanmıyor. Post edilen veriyi $edit değişkenine atmıssınız. Daha sonra bu değişkenin boş gelip gelmediğini kontrol etmişsiniz. Oradaki if koşuluna else durumunu belirtmemişsiniz. Bu sebeple arraydeki edit indexi hata döndürüyor. 91.satırda hangi kod var?

**Comment by abdurrahmanekr** [comment]
Sanmıyorum. $edit değişkenine normalde null geliyor zaten 91.satır input.php:91 
```
public function post($data = null, $xss_clean = true) {
		if($data == null) {
			return $_POST;
		} else {
			if($xss_clean == true) {
				return $this->xss_clean($_POST[$data]); // burası
			} else {
				return $_POST[$data];
			}
		}
	}
```

**Comment by tkaratug** [comment]
Evet ben hata satırını controllerda veriyor gibi düşündüm dalgınlıktan. Normalde zaten postun içi boş gelirse php bunu notice olarak bildiriyor. Bunun önlemini sizin almanız gerekiyor. Bu durumda veri boşsa null dönsün derseniz ileride boş bir veri gelmesinden kaynaklanan hatayı tespit etmek için çok uğraşabilirsiniz. Bunun yerine verinin boş gelip gelmediğini kontrol edip daha sonra işlemeniz daha doğru olacaktır.

**Comment by abdurrahmanekr** [comment]
hmm notice gelmesi gerekir diyorsunuz yani anladım dediğinizi mantıklı geldi :) peki bu kontrolü yapmadan 3. bir paramatre olarak default değer atma gibi bir şey yapabilir miyiz bir öneri aslında. kod bütünlüğünü bozacağını düşünüyorsanız katılırım. Bu arada benim gayet hoşuma gitti özellikle doküman çok hoşuma gitti. Gerçekten iyi bir iş çıkarmışsınız. contributor olmayı isterdim :smile:

**Comment by tkaratug** [comment]
O şekilde olsa da hata ayıklama aşamasında vakit kaybettirir. Hata dönmesi iyidir. Bu şekilde verinin boş geldiğini anlayıp oraya müdahale edebilirsiniz. Görüşleriniz için de teşekkür ederim. Katkıda bulunmak isteyen herkese açığım bu arada :)

**Comment by abdurrahmanekr** [comment]
@tkaratug yalnız hocam şöyle bir şey aklıma geldi ben her zaman o fonksiyonda o değişkeni karşılamayabilirim. Peki bu durumda ne yapılabilir. Ben onu aynı sayfada edit işlemi var mı diye kullandım

**Comment by tkaratug** [comment]
Bu gibi durumlarda önce http ile post request gelip gelmediğini kontrol edin. Eğer gelmişse o zaman edit işlemi ile ilgili kodları bu koşul içine yazarsınız.

**Comment by abdurrahmanekr** [comment]
O değer girildi mi kontrolü gerekiyor bence. Sonuçta o siteye yazılan kod dışında başka request yapılabilir.

**Comment by tkaratug** [comment]
kontrolü kendiniz yapabilirsiniz.

**Comment by abdurrahmanekr** [comment]
işte onu nasıl yapmam gerekir

**Comment by tkaratug** [comment]
form doğrulama pluginini kullanabilirsiniz. 
[http://kilavuz.titanphp.com/validation_plugin.html](url)

**Comment by abdurrahmanekr** [comment]
Aradığım yanıt buydu teşekkürler.
