### ISSUE TITLE
get_referrel fonksiyonunun ismi doküman'a yanlış yazılmış 

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#11]
doğru ismi bu `get_referrer` ama [dokümanda](http://kilavuz.titanphp.com/user_agent_helper.html#get_referral) yanlış yazılmış ya da ikisinden biri

**Comment by tkaratug** [comment]
Uyarın için teşekkürler. Kılavuzdaki hatayı düzelttim.
