### ISSUE TITLE
html_clean methodu ismi clean olarak kaydedilmiş

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#12]
[klavuzda](http://kilavuz.titanphp.com/input_plugin.html#html_clean) $this->input->clean("test") dediğimde şu hatayla karşılaşıyorum 
```
Fatal error: Uncaught Error: Call to undefined method Input::clean()
```
büyük ihtimal ya klavuzdaki isim yanlış ya da koddaki.

**Comment by tkaratug** [comment]
Evet kılavuza yanlış yazmışım. $this->input->html_clean($data) şeklinde kullanılmalı. Kılavuzu düzeltiyorum.
