### ISSUE TITLE
Url'de türkçe karakter problemi

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#13]
Normalde bu yapılabilir mi, bilmiyorum. Ama routers 'de  
```
"aramayap/([a-zA-ZÇŞĞÜÖİçşğüöı]+)"	 => "site/search/index/$1"
```
şeklinde yaptığımda url çalışmıyor. url bölümüne türkçe karakter ekletebilir miyim ?

**Comment by abdurrahmanekr** [comment]
`system/core/App.php` dosyasında `run` fonksiyonunda `$_SERVER['REQUEST_URI']` yi `urldecode` ile çalıştırdığımda oldu ne kadar doğru bilmiyorum

**Comment by tkaratug** [comment]
Türkçe karakterli url kullanmadığım için bu konuyu hiç düşünmemiştim. urldecode, url'deki metni normal metne dönüştürür. Bu şekilde kullanabilirsiniz. Ben de sonraki sürümde bunu sisteme dahil edeceğim. Teşekkürler.

**Comment by abdurrahmanekr** [comment]
Yeni güncellemede yapılmadığını görüyorum. Denediğimde çalıştıramadım @tkaratug

**Comment by tkaratug** [comment]
Bunu unutmuşum kusura bakmayın. v1.1.4 güncellemesine az kaldı. Notlarıma aldım. Bu hafta içinde güncellemiş olurum. Teşekkürler.
