### ISSUE TITLE
htaccess www ya da non-www yapmak

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#14]
Projede www.avarekodcu.com yerine avarekodcu.com da gelebiliyor eğer ben bunlardan sadece birini seçmek istersem nasıl yapardım. 
```
RewriteCond %{HTTP_HOST} !^www\.avarekodcu\.com
RewriteRule (.*) http://www.avarekodcu.com/$1 [R=301,L]
```
denediğimde public dosyasındaki değerlere ulaşamıyor. Seo açısından önemli bir sıkıntı diye düşünüyorum. Teşekkür ederim

**Comment by tkaratug** [comment]
Bu şekilde Titan'ın yapısına göre belirlenmiş olan htaccess'deki yönlendirme kuralını bozmuş oluyorsunuz. RewriteEngine On satırından sonra aşağıdaki kodları ekleyerek deneyin.

```
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteRule ^ http%1://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

**Comment by abdurrahmanekr** [comment]
Teşekkür ederim sorunumu çözdüm :+1:
