### ISSUE TITLE
Css dosyaları veya diğer dosya include işlemlerindeki cache sorunu

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#16]
`$this->template->set_css("style.css");` bu şekilde css dosyasını dahil edebiliyorum. Ama ben
`$this->template->set_css("style.css?v=1");` şeklinde cache sorununa müdahele etmek istediğimde **CSS Style dosyası bulunamadı:** hatası ile karşılaşıyorum. Bununla karşılaşmamak için bir RegExp yazılabilir.

**Comment by tkaratug** [comment]
Asset plugininde gerekli düzenlemeyi yapıp commit ettim. Öneri için teşekkürler.
