### ISSUE TITLE
controller örneği

### ISSUE THREAD

**Issue by zulfu** [tkaratug/titan-mvc#17]
class Haberler extends Controller
{
    public function kategoriler($kategori_ismi, $haber_sayisi)
    {
        echo $kategori_ismi . ' kategorisinde ' . $haber_sayisi . ' adet haber listelendi.';
    }
}
http://ornek.com/haberler/kategoriler/gundem/5
çıktı : haberler kategorisinde gundem adet haber listelendi.

bunun böyle olması normal mi? yoksa son sürümde controller ile ilgili bir değişiklik mi oldu?

**Comment by tkaratug** [comment]
v1.1.0 Sürümünden itibaren controllerlar **/controller** dizininde ayrı dizinler içinde yer alabiliyorlar. Bu değişiklik kapsamında bir bug tespit edip düzelttim. **/system/core/App.php** dosyasını güncellerseniz hata giderilmiş olacaktır. Uyarı için de teşekkürler.
