### ISSUE TITLE
Projeyi ilk kurduğum zaman config dosyası bulunamadı diyor

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#18]
Projede developer modda database'ye bağladığımda **Error Code: 1008** ile karşılaştım. Bu sorunu `app/config/development/` dizinine db.php dosyasını kopyaladığımda çözdüm.

**Comment by tkaratug** [comment]
Prod ve developer modda çalışırken sürekli ayarları değiştirmek zorunda kalmayalım diye bu şekilde ayarladım.

**Comment by abdurrahmanekr** [comment]
Anlıyorum. Herhalde dosya eklenmedi onu belirtmek istedim, peki ne yapmam gerekir. yaptığım doğru mu

**Comment by tkaratug** [comment]
Evet yaptığınız doğru. Developmen ortamına ait ayarlarınız orada durabilir. Böylece remote'da ve local'de ayar değişikliği yapmadan çalışabilirsiniz.

**Comment by abdurrahmanekr** [comment]
Bu dosyayı bu repoya güncelleyecek misiniz yoksa herkes kendi mi ekleyecek

**Comment by tkaratug** [comment]
Environment değeri ilk kurulumda development olduğu için aslında eklesem iyi olacak. v1.1.4 'te bu şekilde gelir.
