### ISSUE TITLE
Özelleştirilebilir Link tag'ı

### ISSUE THREAD

**Issue by abdurrahmanekr** [tkaratug/titan-mvc#19]
Siteme `<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Twitter">` twitterdaki gibi open search eklemek istiyorum bu tagı asset pluginde yapabilir miyim ? $this->asset->set_meta gibi

**Comment by tkaratug** [comment]
set_meta() methodunu örnek alarak kolaylıkla yapabilirsiniz.
