### ISSUE TITLE
config/config.php

### ISSUE THREAD

**Issue by irfanevrens** [tkaratug/titan-mvc#7]
`config/config.php`

Bu dosya App sınıfında içeri alınıyor. Ayrıca, system/plugins/Cookie.php ve system/plugins/Session.php içinde de alınıyor. Gördüğüm kadarıyla config parametrelerine ihtiyaç duyuyor bu sınıflar. Bu config içindeki ayarlara app üzerinden ulaşılırsa kendini tekrar etmeyen bir yapı kurulmuş olur.

Tabi bunun için Cookie ve Session nesneleri oluştururken $app objesi gönderiliyor olmalı.

**Comment by tkaratug** [comment]
Bu konuda ben de aynı fikirdeyim fakat config dosyalarına erişmesi gereken her nesneye app objesini göndermek, pek best practice gibi gelmedi. O yüzden şimdilik bu şekilde bırakıyorum.

**Comment by irfanevrens** [comment]
Aslında burada temel bir problem var. O da merkezi olarak bir service manager'ın olmaması. Sanırım bir service manager geliştirirsek bu problem çözülmüş olur. 

Ayrıca, App bu işin http katmanını yöneten ve MVC pattern'i ile şekillenmiş context'i olabilir. Session ya da Cookie vs bu context'e ulaşmasına çok da gerek yok aslında. Service manager üzerinden dolaylı olarak iletişim sağlanabilir.
