### ISSUE TITLE
Twig veya Smarty Desteği [Feature]

### ISSUE THREAD

**Issue by nusu** [tkaratug/titan-mvc#9]
öncelikle çok tatlı bir yapı olmuş elinize sağlık, çok beğendim.
herhangi bir mvc'nin default olarak bir template engine ile beraber gelmesi çok daha düzgün yapılar kurmamıza yol açıyor,
template engine olarak benim önerim twig.

**Comment by tkaratug** [comment]
Teşekkür ederim. Bir sonraki sürümde template engine eklemeyi düşünüyorum. Benim aklımdan geçen de twig. Bakalım..
